// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScheduleLib.Data;

#nullable disable

namespace ScheduleLib.MigrationService.Migrations
{
    [DbContext(typeof(ScheduleContext))]
    [Migration("20260606160552_20260606a")]
    partial class _20260606a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScheduleLib.Models.EventItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ScheduleItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleItemId");

                    b.ToTable("EventItems");
                });

            modelBuilder.Entity("ScheduleLib.Models.ScheduleEventItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ScheduleItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleItemId");

                    b.ToTable("ScheduleEventItems");
                });

            modelBuilder.Entity("ScheduleLib.Models.ScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ScheduleItems");
                });

            modelBuilder.Entity("ScheduleLib.Models.EventItem", b =>
                {
                    b.HasOne("ScheduleLib.Models.ScheduleItem", "ScheduleItem")
                        .WithMany("EventItems")
                        .HasForeignKey("ScheduleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleItem");
                });

            modelBuilder.Entity("ScheduleLib.Models.ScheduleEventItem", b =>
                {
                    b.HasOne("ScheduleLib.Models.ScheduleItem", "ScheduleItem")
                        .WithMany("ScheduleEventItems")
                        .HasForeignKey("ScheduleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleItem");
                });

            modelBuilder.Entity("ScheduleLib.Models.ScheduleItem", b =>
                {
                    b.Navigation("EventItems");

                    b.Navigation("ScheduleEventItems");
                });
#pragma warning restore 612, 618
        }
    }
}
