<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ScheduleLib.ScheduleRunnerService-b4de7fd1-b882-4ae6-86a7-c045cd54905b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScheduleLib\ScheduleLib.csproj" />
    <ProjectReference Include="..\schedule-app.ServiceDefaults\schedule-app.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
